Updated.
git-svn-id: https://svn.r-project.org/R-dev-web/trunk@2314 c52295ea-58df-0310-926a-d16021944841

diff --git a/QA/CRAN/Kurt/bin/check-R b/QA/CRAN/Kurt/bin/check-R
--- a/QA/CRAN/Kurt/bin/check-R
+++ b/QA/CRAN/Kurt/bin/check-R
@@ -89,6 +89,7 @@ export LANG="en_US.UTF-8"
 export LC_COLLATE=C
 
 do_cleanup_and_exit () {
+  lamwipe -sessionsuffix ${R_flavor} || true
   kill -9 ${Xvfb_pid}
   rm -f ${check_dir}/${R_flavor}/Xvfb.pid
   exit ${1-0}
@@ -287,6 +288,13 @@ done
 ## </NOTE>
 
 ## And now the testing ...
+
+## Start/customize distributed computing environments.
+## Running Rmpi calls lamboot so that at the end we should clean up by
+## calling lamwipe.  Of course, the LAM RTE should be check process
+## specific, which can be accomplished via LAM_MPI_SESSION_SUFFIX.
+export LAM_MPI_SESSION_SUFFIX=${R_flavor}
+
 ## <NOTE>
 ## Could also try eliminating the non local packages which are not to be
 ## checked by something like
