update cuR to support multiple versions
git-svn-id: https://svn.r-project.org/R-dev-web/trunk@2254 c52295ea-58df-0310-926a-d16021944841

diff --git a/QA/Simon/packages/cuR b/QA/Simon/packages/cuR
--- a/QA/Simon/packages/cuR
+++ b/QA/Simon/packages/cuR
@@ -4,8 +4,21 @@
 
 cd "${BASE}"
 
+WHICH=`echo "$1"|sed 's:.tar.gz$::'`
+if [ -z "$WHICH" ]; then
+    WHICH=R-current
+fi
+
+TARBALL="$WHICH.tar.gz"
+if [ ! -e "$TARBALL" ]; then
+    echo "*** ERROR: cannot find the tar-ball $TARBALL"
+    exit 1
+fi
+
+echo "removing previous versions ..."
 # restore current R release for the builds
 rm -rf /Library/Frameworks/R.framework
-tar fxz R-current.tar.gz -C /
+echo "restoring $TARBALL ..."
+tar fxz "$TARBALL" -C /
 
 R --version |grep ^R
