make most scripts oscode-independent
git-svn-id: https://svn.r-project.org/R-dev-web/trunk@2188 c52295ea-58df-0310-926a-d16021944841

diff --git a/QA/Simon/packages/sync-rcheck b/QA/Simon/packages/sync-rcheck
--- a/QA/Simon/packages/sync-rcheck
+++ b/QA/Simon/packages/sync-rcheck
@@ -1,18 +1,25 @@
 #!/bin/sh
 
-# rsync package check results with Phaeton
+# rsync package check results with deployment server
 
 : ${BASE=/Builds/packages}
-#: ${server=urbaneks@rosuda.org}
 : ${server=r.rsync.urbanek.info}
+
+SKIP_R_CHK=1
+
+. ${BASE}/common
+
+if [ -z "${oscode}" ]; then
+    echo "** ERROR: oscode is empty, check your installation."
+    exit 1
+fi
 
 OWD=`pwd`
 cd "$BASE"
 
 versions=`sed -e 's/:.*//' $BASE/vers`
-#chmod a+r tiger-universal/results/2.4.0/*.Rcheck/00*
 for v in $versions; do
-   rsync -avz --delete tiger-universal/results/$v/ ${server}:/R/build/tiger-universal/results/$v/
+   rsync -avz --delete ${oscode}-universal/results/$v/ ${server}:/R/build/${oscode}-universal/results/$v/
 done
 
 cd "$OWD"
