check disk space before building
git-svn-id: https://svn.r-project.org/R-dev-web/trunk@2439 c52295ea-58df-0310-926a-d16021944841

diff --git a/QA/Simon/R-build/buildR b/QA/Simon/R-build/buildR
--- a/QA/Simon/R-build/buildR
+++ b/QA/Simon/R-build/buildR
@@ -85,7 +85,13 @@ fi
 
 echo "Building $RD for $TNAME (arch $TARCH, pkgType=\"${PKGTYPE}\")"
 
-mkdir -p $BASE/$TNAME
+## check available disk space before proceeding - we require at least 1GB to make sure
+DSKF=`df -g "$BASE/$TNAME" | awk '{print $4}' | tail -n 1`
+if [ "$DSFK" = 0 ]; then
+    echo "***FATAL ERROR: out of disk space!"
+    echo "FATAL ERROR: out of disk space" > $BASE/$TNAME/$RD.FAILED
+    exit 1
+fi
 
 rm -f $BASE/$TNAME/$RD-$TNAME-bld.tar.gz
 
@@ -102,6 +108,10 @@ if [ -n "${FORCE_OS_VERSION}" ]; then
 fi
 if [ $TARCH = ppc -a $ARCH = i386 ]; then
     HOST=`echo ${HOST}|sed s/^i386/powerpc/`
+    use_build=yes
+fi
+if [ $TARCH = x86_64 -a $ARCH = i386 ]; then
+    HOST=`echo ${HOST}|sed s/^i386/x86_64/`
     use_build=yes
 fi
 if [ ${use_build} = yes ]; then
