check for packages lock and bail out if there is package build in progress
git-svn-id: https://svn.r-project.org/R-dev-web/trunk@2274 c52295ea-58df-0310-926a-d16021944841

diff --git a/QA/Simon/R-build/common b/QA/Simon/R-build/common
--- a/QA/Simon/R-build/common
+++ b/QA/Simon/R-build/common
@@ -28,3 +28,15 @@ esac
 
 : ${TNAME="$oscode-$ARCH"}
 
+# verify that no packagess are being checked
+PLOCKPATH=/Builds/packages/lock.checking
+if [ -e $PLOCKPATH ]; then
+    LPID=`cat $PLOCKPATH`
+    if ps -p $PLOCKPATH|grep 'mk\.chk'; then
+        echo "**ERROR: package check is in progress, pid $LPID." &1>2
+	exit 1
+    else
+        echo "Stale lock (packages) for pid $LPID, removing"
+        rm -f $PLOCKPATH
+    fi
+fi
