accept TEMPALTE as env var
git-svn-id: https://svn.r-project.org/R-dev-web/trunk@4567 c52295ea-58df-0310-926a-d16021944841

diff --git a/QA/Simon/R4/packaging/mkres b/QA/Simon/R4/packaging/mkres
--- a/QA/Simon/R4/packaging/mkres
+++ b/QA/Simon/R4/packaging/mkres
@@ -1,9 +1,18 @@
 #!/bin/sh
+#
+# Usage: mkres <root> [<template>]
+#
+# <template> defaults to $TEMPLATE or "template" and must be a subdirectory of root
+#
 
 ROOT="$1"
 if [ -z "$1" ]; then
     echo "ERROR: root must be specified" >&2
     exit 1
+fi
+
+if [ -z "$2" -a -z "$TEMPLATE" ]; then
+    TEMPLATE=template
 fi
 
 if [ -z "$VER" ]; then
@@ -16,13 +25,13 @@ if [ -z "$GUIVER" ]; then
     exit 1
 fi
 
-if [ ! -e "$ROOT/template/dist.plist" ]; then
-    echo "ERROR: invalid root, $ROOT/template/dist.plist is missing" >&2
+if [ ! -e "$ROOT/$TEMPLATE/dist.plist" ]; then
+    echo "ERROR: invalid root or template, $ROOT/$TEMPLATE/dist.plist is missing" >&2
     exit 1
 fi
 
-for i in `find "$ROOT/template" -name \*plist -or -name \*rtf`; do
-    dst=`echo $i | sed s:/template::`
+for i in `find "$ROOT/$TEMPLATE" -name \*plist -or -name \*rtf`; do
+    dst=`echo $i | sed s:/$TEMPLATE::`
     echo $i '->' $dst
     sed -e "s/%VER%/$VER/g" -e "s/%VERFULL%/$VERFULL/g" -e "s/%GUIVER%/$GUIVER/g" $i > $dst
 done
